/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oovp.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author lenov
 */
public class Customerss extends javax.swing.JFrame {
    Connection Con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement St = null;
    public Customerss() {
        initComponents();
        DisplayCustomers();
    }
private void DisplayCustomers(){
    try {
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petshopproject", "root", "");
        Statement St = (Statement) Con.createStatement();
        ResultSet rs = St.executeQuery("SELECT * FROM customers");
        Customers.setModel(DbUtils.resultSetToTableModel(rs));
    } 
    catch (SQLException e) {
    // Handle SQLException appropriately
    e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CustName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CustAddress = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CustPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CustSave = new javax.swing.JButton();
        CustEdit = new javax.swing.JButton();
        CustDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Customers = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PetsO = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CategoriesO = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BillingsO = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UsersO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Manage Customers");

        jLabel14.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel14.setText("Name");

        CustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNameActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel16.setText("Address");

        CustAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustAddressActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel17.setText("Phone");

        CustPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustPhoneActionPerformed(evt);
            }
        });

        CustSave.setBackground(new java.awt.Color(255, 153, 0));
        CustSave.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        CustSave.setText("Save");
        CustSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustSaveActionPerformed(evt);
            }
        });

        CustEdit.setBackground(new java.awt.Color(255, 153, 0));
        CustEdit.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        CustEdit.setText("Edit");
        CustEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustEditActionPerformed(evt);
            }
        });

        CustDelete.setBackground(new java.awt.Color(255, 153, 0));
        CustDelete.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        CustDelete.setText("Delete");
        CustDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustDeleteActionPerformed(evt);
            }
        });

        Customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category", "Quantity", "Price"
            }
        ));
        Customers.setSelectionBackground(new java.awt.Color(255, 153, 0));
        Customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Customers);

        jLabel19.setFont(new java.awt.Font("Maiandra GD", 0, 30)); // NOI18N
        jLabel19.setText("Customers List");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(CustSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(CustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(CustPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 182, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 30)); // NOI18N
        jLabel2.setText("IRONIC PET SHOP");

        PetsO.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        PetsO.setText("Pets");
        PetsO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PetsOMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        jLabel7.setText("Customers");

        CategoriesO.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        CategoriesO.setText("Categories");
        CategoriesO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriesOMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        BillingsO.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        BillingsO.setText("Billings");
        BillingsO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillingsOMouseClicked(evt);
            }
        });

        UsersO.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        UsersO.setText("Users");
        UsersO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(10, 10, 10))
                                .addComponent(jLabel10))
                            .addComponent(jLabel8)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(PetsO)
                            .addComponent(CategoriesO)
                            .addComponent(Logout)
                            .addComponent(BillingsO)
                            .addComponent(UsersO))))
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(UsersO))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(CategoriesO))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel8)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel10)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(PetsO)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43)
                        .addComponent(BillingsO)
                        .addGap(61, 61, 61)
                        .addComponent(Logout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustNameActionPerformed

    private void CustAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustAddressActionPerformed

    private void CustPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustPhoneActionPerformed
    int ItemId;
    Statement st1 = null;
    ResultSet rs1 = null;
    private void CountIt(){
        try{
            st1 = (Statement) Con.createStatement();
            rs1 = st1.executeQuery("select Max(CustID) from customers");
            rs1.next();
            ItemId = rs1.getInt(1)+1;
        }
        catch (Exception e) {
   
        }
    }
    private void CustSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustSaveActionPerformed
        if (CustName.getText().isEmpty() || CustAddress.getText().isEmpty() || CustPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else
            try {
                CountIt();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petshopproject", "root", "");
                PreparedStatement Save = (PreparedStatement) Con.prepareStatement("Insert into customers value(?,?,?,?)");
                Save.setInt(1, ItemId);
                Save.setString(2, CustName.getText());
                Save.setString(3, CustAddress.getText());
                Save.setString(4, CustPhone.getText());
                int row = Save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer Added");
                Con.close();
                DisplayCustomers();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_CustSaveActionPerformed
    private void Clear()
    {
        CustName.setText("");
        CustAddress.setText("");
        CustPhone.setText("");
    }
    private void CustEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustEditActionPerformed

        if (CustName.getText().isEmpty() || CustAddress.getText().isEmpty() || CustPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petshopproject", "root", "");
                PreparedStatement Save = (PreparedStatement) Con.prepareStatement("update customers set CustName=?, CustAddress=?, CustPhone=? where CustID=?");
                Save.setInt(4, key);
                Save.setString(1, CustName.getText());
                Save.setString(2, CustAddress.getText());
                Save.setString(3, CustPhone.getText());
                int row = Save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer Updated");
                Con.close();
                DisplayCustomers();
                Clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_CustEditActionPerformed

    private void CustDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustDeleteActionPerformed
        if (key == 0){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petshopproject", "root", "");
                PreparedStatement Save = (PreparedStatement) Con.prepareStatement("delete from customers where CustID=?");
                Save.setInt(1, key);
          
                int row = Save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer Deleted");
                Con.close();
                DisplayCustomers();
                Clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_CustDeleteActionPerformed

    int key = 0;
    private void CustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersMouseClicked
        DefaultTableModel model = (DefaultTableModel) Customers.getModel();
        int Myindex = Customers.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(Myindex, 0).toString());
        CustName.setText(model.getValueAt(Myindex, 1).toString());
        CustAddress.setText(model.getValueAt(Myindex, 2).toString());
        CustPhone.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_CustomersMouseClicked

    private void UsersOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersOMouseClicked
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UsersOMouseClicked

    private void CategoriesOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriesOMouseClicked
        new Caategories1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoriesOMouseClicked

    private void PetsOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetsOMouseClicked
        new Lobby().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PetsOMouseClicked

    private void BillingsOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillingsOMouseClicked
        new Billing1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BillingsOMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customerss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customerss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customerss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customerss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customerss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BillingsO;
    private javax.swing.JLabel CategoriesO;
    private javax.swing.JTextField CustAddress;
    private javax.swing.JButton CustDelete;
    private javax.swing.JButton CustEdit;
    private javax.swing.JTextField CustName;
    private javax.swing.JTextField CustPhone;
    private javax.swing.JButton CustSave;
    private javax.swing.JTable Customers;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel PetsO;
    private javax.swing.JLabel UsersO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
